services:
  - type: redis
    name: anti-fraude-redis
    ipAllowList: [] # allow all
    plan: free

  - type: web
    name: anti-fraude-api
    env: node
    buildCommand: npm install && npx prisma generate --schema=apps/api/prisma/schema.prisma && npm run build --workspace api
    startCommand: npm run start --workspace api
    envVars:
      - key: NODE_ENV
        value: staging
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
        # Crie um banco Neon via dashboard e cole a URL de conexão aqui no env do render após deploy
      - key: REDIS_URL
        fromService:
          type: redis
          name: anti-fraude-redis
          property: connectionString

  - type: worker
    name: anti-fraude-worker
    env: node
    buildCommand: npm install && npx prisma generate --schema=apps/api/prisma/schema.prisma && npm run build --workspace worker
    startCommand: npm run start --workspace worker
    envVars:
      - key: NODE_ENV
        value: staging
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: anti-fraude-redis
          property: connectionString

  - type: web
    name: anti-fraude-web
    env: node
    buildCommand: npm install && npm run build --workspace web
    startCommand: npm run start --workspace web
    envVars:
      - key: NODE_ENV
        value: staging
      - key: NEXT_PUBLIC_API_URL
        value: https://anti-fraude-api.onrender.com
